services:
  db:
    image: postgres:18
    environment:
      POSTGRES_DB: shake-assistant-db
      POSTGRES_USER: shake
      POSTGRES_PASSWORD: dev-only
    ports:
      - "5532:5432"
    volumes:
      - postgres_data:/var/lib/postgresql

volumes:
  postgres_data:
