package com.shake.octo.orchestrator;

import org.springframework.ai.tool.annotation.ToolParam;

import java.util.List;

/**
 * The orchestrator's decomposed plan for fulfilling a user request.
 *
 * <p>Plans are not constructed in code — they are generated by the LLM as structured output
 * when it invokes the {@code executePlan} tool. The LLM receives the list of available
 * subagents and produces an {@code ExecutionPlan} whose tasks are dispatched by {@link PlanExecutor}.
 *
 */
public record ExecutionPlan(
        @ToolParam(description = "a short, human-readable summary of the execution flow: name the subagents" +
                " involved, and state which tasks run in parallel and which wait for others to finish." +
                " Must be consistent with the dependencies declared below.")
        String executionSummary,
        @ToolParam(description = "list of tasks to be executed")
        List<AgentTask> agentTasks)
{
}
